from pydantic import BaseModel, Field, model_validator
from datetime import date
from typing import Optional, Self

class SessionCreate(BaseModel):
    """
        Schema for creating a new session.

        Validates dates and automatically initializes the status based on
        the current date and the session start/end dates.

        Attributes:
            teacher_id: int: Identifier of the trainer responsible for the session.
            course_id: int: Course ID associated with the session.
            start_date: date: Date the session started.
            end_date: date: Date the session ended.
            capacity: int: Number of students in the session.
            status: int: Status of the session. Initialized automatically based on the dates if not provided.
    """
    teacher_id: int
    course_id: int
    start_date: date
    end_date: date
    capacity: int = Field(gt=0)
    status: Optional[int] = Field(default=None, ge=0, le=2)

    @model_validator(mode='after')
    def check_dates(self) -> Self:
        """
        Valid only if the end date is later than the start date.

        Raises:
            ValueError: If end_date <= start_date.

        Returns:
            Self: The validated instance.
        """
        if self.end_date <= self.start_date:
            raise ValueError('The end date must be later than the start date')
        return self

    @model_validator(mode='after')
    def set_status(self) -> Self:
        """
            Automatically initializes the session status based on the dates.

            The status is defined according to the following rules:
                - 0 (Planned) : If start_date > today
                - 1 (Ongoing) : If start_date <= today < end_date
                - 2 (Done) : If end_date < today

            If a status is explicitly provided, it is not changed.

            Returns:
                Self: The instance with the initialized status.
        """
        today = date.today()

        if self.status is None:
            if self.end_date < today:
                self.status = 2  # Done
            elif self.start_date > today:
                self.status = 0  # Planned
            else:
                self.status = 1  # Ongoing

        return self

class SessionRead(SessionCreate):
    """
        Schema for reading/retrieving a session from the database.

        Attributes:
            id (int): Unique identifier of the session (auto-generated by database).
            teacher_id (int): ID of the instructor responsible for the session.
            course_id (int): ID of the associated course.
            start_date (date): Start date of the session.
            end_date (date): End date of the session.
            capacity (int): Number of available seats in the session.
            status (int): Current status of the session (0=Planned, 1=Ongoing, 2=Done).
    """
    id: int
    teacher_id: int
    course_id: int
    start_date: date
    end_date: date
    capacity: int
    status: int

class SessionUpdate(BaseModel):
    """
        Schema for partial updates to an existing session.

        Attributes:
            teacher_id (Optional[int]): ID of the instructor. If None, field is not updated.
            course_id (Optional[int]): ID of the course. If None, field is not updated.
            start_date (Optional[date]): New start date. If None, field is not updated.
            end_date (Optional[date]): New end date. If None, field is not updated.
            capacity (Optional[int]): Number of available seats. Must be > 0 if provided.
                If None, field is not updated.
            status (int): New status for the session (0=Planned, 1=Ongoing, 2=Done).
                This field is required and will override auto-calculated values.
    """
    teacher_id: Optional[int] = None
    course_id: Optional[int] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    capacity: Optional[int] = Field(default=None, gt=0)
    status: Optional[int] = Field(default=None, ge=0, le=2)

    @model_validator(mode='after')
    def set_status(self) -> Self:
        """
            Automatically recalculates the session status based on the dates.

            The status is defined according to the following rules:
                - 0 (Planned) : If start_date > today
                - 1 (Ongoing) : If start_date <= today < end_date
                - 2 (Done) : If end_date < today

            If a status is explicitly provided, it is not changed.

            Returns:
                Self: The instance with the initialized status.
        """
        if (self.start_date is not None or self.end_date is not None) and self.status is None:
            today = date.today()

            if self.status is None:
                if self.end_date < today:
                    self.status = 2  # Done
                elif self.start_date > today:
                    self.status = 0  # Planned
                else:
                    self.status = 1  # Ongoing

        return self